# Generated by Django 6.0.2 on 2026-03-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', 'id'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='auditlogs_a_target__f518a1_idx'), models.Index(fields=['action'], name='auditlogs_a_action_b1f2ec_idx'), models.Index(fields=['timestamp'], name='auditlogs_a_timesta_61f129_idx')],
            },
        ),
    ]
