# Generated by Django 6.0.2 on 2026-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
