# Generated by Django 6.0.2 on 2026-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='booking_mode',
            field=models.CharField(choices=[('BEDSPACE', 'Bedspace (1 slot)'), ('WHOLE_ROOM', 'Whole room only')], default='BEDSPACE', max_length=20),
        ),
    ]
