# Generated by Django 6.0.2 on 2026-03-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_roomtype_booking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='held',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
