# Generated by Django 6.0.2 on 2026-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_alter_hostel_options_alter_hostel_location_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['hostel', 'name', 'id']},
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='roomtype_capacity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('booked__gte', 0)), name='roomtype_booked_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('held__gte', 0)), name='roomtype_held_gte_0'),
        ),
    ]
