# Generated by Django 6.0.2 on 2026-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_accesscode_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SEPARATED', 'Separated'), ('RETAINED', 'Retained')], default='PENDING', max_length=20),
        ),
    ]
